### ISSUE TITLE
Highlights only zero-width spaces on Windows

### ISSUE THREAD

**Issue by TuureKaunisto** [TuureKaunisto/highlight-dodgy-chars#1]
Tested on Windows 7

All the other special characters seem to be ignored.

**Comment by jstalnak** [comment]
I can confirm this. Using ST3 Stable Build 3083, Windows 7 Enterprise, SP1, fully patched,  I simply don't see any special characters highlighted. Using this as a test:

<quote>
1.       Please create a BI KB using the basic documentation I created and linked in Box (see email below).  Please include tags for this KB that include: “BI” “Business Insight” “Reports” and “Cognos”
</quote> 

No hightlights. Doing a quick run down through the Alt-Keyboard# set I see:

From:

http://symbolcodes.tlt.psu.edu/accents/codealt.html

In order down the page:

ÀÈÌÒÙàèìòùÁÉÍÓÚÝáéíóúýÂÊÎÔÛâêîôûÃÑÕãñõÄËÏÖÜŸäëïöüÿ
¡¿ÇçŒœßºªØøÅåÆæÞþÐð«»‹›ŠšŽž
¢£€¥ƒ¤
÷°¬±µ‰
¼½¾
©®™•§†‡–—¶

Only the TM mark is highlighted; all others are not.

From:

http://www.alt-codes.net/

Skipping the normal ASCII set (letters, numbers, symbols) as I remember them:

Alt-1 through Alt-31

Only four of these are NOT highlighted: 4, 19,20, 21

☺☻♥♦♣♠•◘○◙♂♀♪♫☼►◄↕‼¶§▬↨↑↓→←∟↔▲▼

These are highlighted:

127, 158 169, 176, 177, 178 and all of the line characters 179-223

⌂₧⌐░▒▓│┤╡╢╖╕╣║╗╝╜╛┐└┴┬├─┼╞╟╚╔╩╦╠═╬╧╨╤╥╙╘╒╓╫╪┘┌█▄▌▐▀

None of the Greek chars are hightlighted except 236, the infinity sign

αßΓπΣσµτΦΘΩδ∞φε

The math symbols are highlighted except: 241, 246, 248, 250, 252, 253

∩≡±≥≤⌠⌡÷≈°∙·√ⁿ²■

**Comment by TuureKaunisto** [comment]
Thanks for your thorough report of the bug!

**Comment by jstalnak** [comment]
My pleasure. I really want this to work LOL I get a fair bit of email which form the basis for Knowledge Base documents. Outlook inserts non-standard characters for ' and " and I always forget to take them out. Which, when used in my markdown-2-html process, produce very ugly results. I'm hoping your plugin will help me "see" them and thus not forget. I just learned of your plugin via Josh and SublimeTextTips.com.

Regards,

Guy

## 

Guy Stalnaker, PaCS@DOIT, ECM/Imaging Service Lead
115 N. Orchard Street, Room 305 RS, Madison WI 53715
guy.stalnaker​@wisc.edu, work 608.263.8035

------ Original Message ------

**Comment by jstalnak** [comment]
Just a follow up - how can I get your updated plugin installed in my SimpleText? I've tried downloading from the git repo and just putting the files in the SimpleText directory structure, in multiple places, but that doesn't seem to work. As of this morning the version available via PackageManager still does not seem to work for me.

Thanks.

## 

Guy Stalnaker, PaCS@DOIT, ECM/Imaging Service Lead
115 N. Orchard Street, Room 305 RS, Madison WI 53715
guy.stalnaker​@wisc.edu, work 608.263.8035

------ Original Message ------

**Comment by TuureKaunisto** [comment]
Glad you brought this up since I just assumed this worked based on my own tests. The package manager should update your version automatically.

You can check the version you have installed by hitting Ctrl + Shift + p and typing `Package Control: List Packages`. Under the Highlight Dodgy Chars plugin you should see a description and a version number. The number should be 0.0.6

I tested also by copying and pasting your original comment to Sublime. It highlighted most of the characters and those that weren't highlighted were a part of the European special chars that are whitelisted by default.

Which version of Sublime Text are you using? The plugin was developed for Sublime Text 3 and hasn't been tested on other versions.

**Comment by jstalnak** [comment]
At some point during the day there was an update and I'm now at 0.0.6 and the characters ARE highlighted. I'm delighted!

Thanks for creating the tool.

Regards.

## 

Guy Stalnaker, PaCS@DOIT, ECM/Imaging Service Lead
115 N. Orchard Street, Room 305 RS, Madison WI 53715
guy.stalnaker​@wisc.edu, work 608.263.8035

------ Original Message ------
