### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by kpym** [TuureKaunisto/highlight-dodgy-chars#2]
I'm running Sublime Text 2 on Windows 7 and I have the following error when plugin starts: 

```
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 62, in reload_plugin
  File ".\HighlightDodgyChars.py", line 36
SyntaxError: Non-ASCII character '\xc2' in file .\HighlightDodgyChars.py on line 36, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```

If I save `HighlightDodgyChars.py` with BOM or if I add (followin the [PEP](http://www.python.org/peps/pep-0263.html))

```
#!/usr/bin/python
# -*- coding: utf-8 -*-
```

at the beginning of the document the error disappear.

**Comment by TuureKaunisto** [comment]
Thanks for the fix! I'll add this once I have time. You can also make a pull-request of the fix if you want to help.
