### ISSUE TITLE
Could you add test.txt somewhere for testing?

### ISSUE THREAD

**Issue by Arkkimaagi** [TuureKaunisto/highlight-dodgy-chars#4]
It would be handy to have this file in textual mode somewhere.

![test.txt](https://github.com/TuureKaunisto/highlight-dodgy-chars/raw/master/screen-shot.png)

**Comment by TuureKaunisto** [comment]
The file is now available in the repository:
https://github.com/TuureKaunisto/highlight-dodgy-chars/blob/master/examples.txt
