### ISSUE TITLE
Not showing up in Package Control install menu in Sublime

### ISSUE THREAD

**Issue by lacymorrow** [TuureKaunisto/highlight-dodgy-chars#5]
Was about to write my own and found this, is it maintained?
We should re-submit to package control.

**Comment by TuureKaunisto** [comment]
I wonder if it was just a glitch you were experiencing. It seems to be available in package control and there have been some downloads yesterday. https://packagecontrol.io/packages/Highlight%20Dodgy%20Chars

**Comment by lacymorrow** [comment]
Probably on my end then, thanks!
