### ISSUE TITLE
Linter mode

### ISSUE THREAD

**Issue by Kami-no** [TuureKaunisto/highlight-dodgy-chars#8]
It would be nice to have it as linter that will show "issues" in the bottom.

**Comment by TuureKaunisto** [comment]
Sure. I'm no longer using Sublime myself so maintaining this plugin is not a priority for me but if someone makes a PR of a feature like this I'll try to find time to review it and merge if I think it's decent.

However, I think porting this whole plugin to for example [SublimeLinter](http://www.sublimelinter.com/en/stable/) would make a lot more sense.
